#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh" $@

access_token="$(
  curl -sL -X POST "${ENDPOINT_TOKEN}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "client_id=${CLIENT_ID}" \
    -d "client_secret=${CLIENT_SECRET}" \
    -d "grant_type=client_credentials" |
    jq -r ".access_token"
)"

if [[ "${decode}" == "true" ]]; then
  echo "${access_token}" | decode_token
else
  echo "${access_token}"
fi
