#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh" $@

response="$(
  curl -sL -X POST "${ENDPOINT_TOKEN}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "client_id=${USER_CLIENT_ID}" \
    -d "username=${USER_NAME}" \
    -d "user_id=${USER_NAME}" \
    -d "password=${USER_PASS}" \
    -d "grant_type=password"
)"

display "${response}"
