#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh" $@

params=""
params+="client_id=${CLIENT_ID}"
params+="&client_secret=${CLIENT_SECRET}"
params+="&grant_type=client_credentials"

req "${params}"
