#!/bin/bash
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${scriptdir}/_lib.sh" $@

access_token="$(get_user_access_token)"

response="$(
  curl -Ls -X GET "${KEYCLOAK_HOST}/admin/realms/${KEYCLOAK_REALM}/users/?username=${USER_NAME}" \
    -H "Content-Type: application/json" \
    -H "Authorization: bearer ${access_token}"
)"

display "${response}" -f
