[keycloak]
realm = "master"
host = "https://my-keycloak.idp:4444"

[client]
id = "client_id"
secret = "A_VERY_SECRET_SECRET"

[user]
name = "user_name"
pass = "A_VERY_SECRET_PASS"
client_id = "client_id"
