[keycloak]
realm = "master"
host = "https://my-keycloak.idp:4444"
oidc_url = "${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect"


[client]
id = "client_id"
secret = "A_VERY_SECRET_SECRET"

[user]
name = "user_name"
pass = "A_VERY_SECRET_PASS"
client_id = "client_id"
